name: Build Android APK
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -o TamagotchiV2_QuickTest_TLFolder_FRESH.zip
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: gradle/actions/setup-gradle@v3
      - run: cd TamagotchiLaMichoacana && gradle clean assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: TamagotchiLaMichoacana/app/build/outputs/apk/debug/app-debug.apk
